name: ci-dev

on:
  push:
    branches:
      - develop

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      run_build: ${{ steps.check_flag.outputs.run_build }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for --no-ci flag in commit message
        id: check_flag
        run: |
          echo "Checking commit message for --no-ci flag..."
          if echo "${{ github.event.head_commit.message }}" | grep -- '--no-ci'; then
            echo "::set-output name=run_build::false"
          else
            echo "::set-output name=run_build::true"
          fi

  build:
    needs: init
    if: needs.init.outputs.run_build == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract short SHA
        id: get_sha7
        run: echo "::set-output name=short::$(echo ${{ github.sha }} | cut -c1-7)"
        
      - name: Publish as GitHub Package
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}-dev:latest
            ghcr.io/${{ github.repository }}-dev:${{ steps.get_sha7.outputs.short }}
