name: release

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tag name
        id: get_version
        run: echo "::set-output name=image_version::${GITHUB_REF#refs/tags/}"

      - name: Check tag format
        run: |
          TAG_NAME="${{ steps.get_version.outputs.image_version }}"
          if ! [[ "$TAG_NAME" =~ ^v[0-9]+\.[0-9]+(\.[0-9]+)?$ ]]; then
            echo "Tag $TAG_NAME does not meet the required format 'vX.Y.Z'."
            exit 1
          fi

      - name: Publish as GitHub Package
        uses: docker/build-push-action@v5
        with:
          provenance: false
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ steps.get_version.outputs.image_version }}

      - name: Create Release
        if: success()
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.get_version.outputs.image_version }}
          name: Release ${{ steps.get_version.outputs.image_version }}
          token: ${{ secrets.GITHUB_TOKEN }}
