name: release

on:
  push:
    tags:
      - "v*"

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      is_valid_branch: ${{ steps.check_branch.outputs.is_valid }}
    steps:
      - name: Check if the branch is valid
        id: check_branch
        env:
          ALLOWED_BRANCH: "main"
        run: |
          CURRENT_BRANCH="${GITHUB_REF#refs/heads/}"
          if [[ "$CURRENT_BRANCH" == "$ALLOWED_BRANCH" ]]; then
            echo "is_valid=true" >> $GITHUB_OUTPUT
          else
            echo "is_valid=false" >> $GITHUB_OUTPUT
          fi

  build:
    needs: init
    if: ${{ needs.init.outputs.is_valid_branch == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tag name
        run: echo "image_version=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Check tag format
        run: |
          TAG_NAME="${{ env.image_version }}"
          if ! [[ "$TAG_NAME" =~ ^v[0-9]+\.[0-9]+(\.[0-9]+)?$ ]]; then
            echo "Tag $TAG_NAME does not meet the required format 'vX.Y.Z'."
            exit 1
          fi

      - name: Publish as GitHub Package
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ env.image_version }}

      - name: Create Release
        if: success()
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.image_version }}
          name: Release ${{ env.image_version }}
          token: ${{ secrets.GITHUB_TOKEN }}
